#!/usr/bin/env python3.10
import click

from pytube import YouTube


def download(URL: str, path: str) -> None:
    yt = YouTube(URL)
    streams = yt.streams.filter(
        file_extension="mp4",
        res="720p",
        progressive=True
    )
    for stream in streams:
        stream.download(output_path=path)


@click.command()
@click.argument("path", type=click.STRING)
@click.argument("list_of_videos", type=click.STRING)
def main(path: str, list_of_videos: str) -> None:
    with open(file=list_of_videos, mode="r") as f:
        urls = f.readlines()
    for url in urls:
        download(url, path)


if __name__ == "__main__":
    main()
