#!/usr/bin/env python3.10
from os import path
import pathlib
import click

from bs4 import BeautifulSoup


def extract_youtube_links(file_path: str) -> list:
    with open(file_path, "r") as f:
        html_doc = f.read()
    soup = BeautifulSoup(html_doc, "html.parser")
    result = []
    for link in soup.find_all("a"):
        href: str = link.get("href")
        if href.startswith("https://youtu"):
            result.append(href)
    return result


@click.command()
@click.argument("dir", type=click.STRING)
def main(dir: str) -> None:
    p = pathlib.Path(dir).glob("*.html")
    files = [x for x in p if x.is_file()]
    
    links = []
    for file_path in files:
        links += extract_youtube_links(file_path)
    with open("list_of_videos.txt", mode="w", encoding="utf-8") as f:
        for link in links:
            f.write(link)
            f.write("\n")

    


if __name__ == "__main__":
    main()
